const LunchRecipesList = [
  {
    id: 1,
    type: "lunch",
    category: "oriental",
    country: "Yemeni",
    title: "Mandi",
    description:
      "A traditional dish that originated from Hadhramaut, Yemen, consisting mainly of meat and rice with a special blend of spices",
    getImageSrc: () => require("../images/mandi.jpg"),
    ingrediants: [
      "1 kg chicken legs",
      "1/2 kg Basmati rice",
      "onion",
      "salt",
      "paper",
      "A stick of cinnamon",
      "5 grains of cloves",
      "5 grains of cardamom",
      "half a cup of oil",
      "piece of charcoal",
    ],
    preparation_steps: [
      "1- Boil the chicken",
      "2- Put in the spice bowl with half a cup of oil",
      "3- Pour in chicken stock for every cup and a half",
      "4- Put salt to taste",
      "5- Pour the rice into the pot after it boils",
      "6- Reduce the fire and leave it for a third of an hour",
      "7- Paint the chicken red and put it in the oven for a quarter of an hour",
      "8- Light a charcoal and place it over the rice for 5 minutes and turn off the heat",
    ],
    side_dishes: "Salad and Yogurt",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [20, 30, 50, 65, 80],
    created_at: {
      order: "1",
    },
  },
  {
    id: 2,
    type: "lunch",
    category: "oriental",
    country: "Syrian",
    title: "Shakrya",
    description: "famous traditional syrian lunch meal cooked in special days",
    getImageSrc: () => require("../images/shakrya.webp"),
    ingrediants: [
      "1 kg meat",
      "2 kg yogurt",
      "onion",
      "corn flour",
      "salt",
      "paper",
      "1 piece of egg",
    ],
    preparation_steps: [
      "1- Boil the meat",
      "2- Put the yogurt in a blender with an egg and 4 tablespoons of corn flour",
      "3- Put the previous mixture in a pot on the fire, stirring constantly, until it boils",
      "4- Add salt as desired",
      "5- Put the boiled meat pieces over the milk and let it boil for 5 minutes and turn off the heat",
    ],
    side_dishes: "Rice with vermicelli",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [40, 55, 70, 90, 110],
    created_at: {
      order: "2",
    },
  },
  {
    id: 3,
    type: "lunch",
    category: "western",
    country: "French",
    title: "Cordon Blu",
    description:
      "a dish of meat wrapped around cheese, then breaded and pan-fried or deep-fried",
    getImageSrc: () => require("../images/cordon_blu.jpg"),
    ingrediants: [
      "2 small chicken breasts",
      "Salt and pepper",
      "4 slices swiss cheese",
      "4 to 6 slices of ham",
      "panko breadcrumbs",
      "oil spray",
      "3 tbsp mayonnaise",
      "1 1/2 tbsp Dijon mustard",
      "1 egg",
      "2 tsp plain flour",
    ],
    preparation_steps: [
      "1- Preheat oven to 200C",
      "2- Spread panko breadcrumbs on a baking tray and spray with oil. Bake for 3 minutes or until light golden. Remove and scrape into bowl straight away",
      "3- Cut a pocket into each chicken breast, as per the photo below",
      "4- Fold the cheese in half and place 2 pieces inside each pocket. Do the same with the ham. Close the pocket, seal with 2 toothpicks. Sprinkle with salt and pepper",
      "5- Mix the mayonnaise, mustard, salt and pepper in a bowl. Spread onto the top and sides of the chicken (not underside)",
      "Sprinkle panko over the chicken, using your other hand to press the breadcrumbs onto the side of the chicken. Spray with oil",
    ],
    side_dishes: "Boiled vegetables",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [60, 100, 150, 190, 230],
    created_at: {
      order: "3",
    },
  },
  {
    id: 4,
    type: "lunch",
    category: "western",
    country: "Russian",
    title: "Chicken Stroganoff",
    description:
      "A delicious mixture of butter with chicken and mushrooms, topped with rich cream",
    getImageSrc: () => require("../images/chicken_stroganoff.jpg"),
    ingrediants: [
      "1 kg checken breast",
      "a cup of cooking cream",
      "butter",
      "half cube of Maggi",
      "2 onion",
      "6 garlic",
      "fresh mushrooms",
      "sweet corn",
      "2 spoons of mastard",
      "spoon of corn flour",
      "salt",
      "paper",
      "paprika",
    ],
    preparation_steps: [
      "1- Cut the onion slices and crush the garlic",
      "2- Cut the chicken into slices and season with salt, pepper and paprika",
      "3- put a small piece of butter in a bowl and fry the mushrooms and set them aside",
      "4- Put a second piece of butter and toast the onions in it",
      "5- Place the chicken on top of the onions",
      "6- Add mushrooms, corn, garlic, mustard and Maggi",
      "7- Put water over the chicken, lower the heat, and leave for half an hour",
      "8- Put the flour and then pour the cooking cream",
      "9- Leave them for two minutes and then pour",
    ],
    side_dishes: "White rice or Pasta",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [80, 90, 100, 120, 150],
    created_at: {
      order: "4",
    },
  },
  {
    id: 5,
    type: "lunch",
    category: "oriental",
    country: "Syrian",
    title: "Chicken Shawarma",
    description:
      "a popular street food that is traditionally made in the form of spiced meats that are stacked on a vertical rotisserie with thin slices shaved off as it rotates.",
    getImageSrc: () => require("../images/chicken_shawarma.jpg"),
    ingrediants: [
      "1 kg chicken breast",
      "olive oil",
      "garlic",
      "lemon",
      "salt",
      "paper",
      "cumin",
      "paprika",
      "yogurt",
    ],
    preparation_steps: [
      "1- Mix marinade - For convenience, just mix the marinade directly in a ziplock bag. A bag works best because the chicken remains nicely coated in the marinade. If you prefer to use a container, either turn the chicken a few times or increase the marinade by 50%",
      "2- Add chicken into the marinade. Seal the bag, removing excess air, then massage to coat from the outside. Leave to marinade for 12 to 24 hours in the fridge. If you’re pressed for time, even 3 hours will do!",
      "3- Make the yogurt sauce simply by mixing the ingredients then set aside for at least 20 minutes to let the flavours meld. This will keep for 3 days in the fridge",
      "4- Cook chicken either on the stove or on the BBQ. It will get a great crust on it from the spices, and you will adore the smell. It’s intoxicating!",
      "5- Rest chicken for at least 3 minutes before serving to allow the juices to redistribute throughout the flesh, else they will just run out everywhere when you slice the meat.",
      "6- To serve, just pile everything on a platter and let everybody make their own wraps! The chicken, lettuce, tomato slices, onion, yogurt sauce and warmed flatbreads – homemade or store bought. If the chicken is on the larger side, I sometimes slice it. But if they are smaller, I tend to just leave them whole.",
    ],
    side_dishes: "Garlic cream",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [25, 45, 60, 90, 120],
    created_at: {
      order: "5",
    },
  },
  {
    id: 6,
    type: "lunch",
    category: "oriental",
    country: "Lebanese",
    title: "Shish Tawook",
    description:
      "tender and juicy chicken that's been marinating in earthy spices, yogurt, lemon juice and garlic",
    getImageSrc: () => require("../images/shish_tawook.jpg"),
    ingrediants: [
      "1 kg cubes of chicken breast",
      "yogurt",
      "lemon juice",
      "6 garlic",
      "tomato paste",
      "paprika",
      "cinnamon",
      "oregano",
      "ginger",
      "tenderizer",
    ],
    preparation_steps: [
      "1- Mix all the ingrediants together and you'll get this orangey creamy color ready for you to coat the chicken with",
      "2- Add the large cubes of chicken breast to the marinade and make sure that everything is well coated. While the yogurt and lemon are crucial parts of the flavor of this dish, they also act as a tenderizer for the chicken.",
      "3- Let it marinate for at least 4 hours or overnight.",
      "4- Skewer the chicken right before you’re ready to cook it. I like adding chunks of white onions on each skewer to eat with the sandwich. I love how onions get sweeter when they’re grilled…the perfect vegetable with this shish tawook.",
    ],
    side_dishes: "garlic cream",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [40, 75, 100, 140, 170],
    created_at: {
      order: "6",
    },
  },
  {
    id: 7,
    type: "lunch",
    category: "oriental",
    country: "Egyption",
    title: "Mulukhiyah",
    description:
      "It is one of the favorite dishes in the Arab world, and it spread in Egyptian cuisine and from there to Arab kitchens",
    getImageSrc: () => require("../images/mulukhiyah.jpg"),
    ingrediants: [
      "Half a kilo of minced molokhia",
      "A quantity of water according to the required density",
      "One and a half tablespoons of finely chopped garlic",
      "One and a half tablespoons of ground dried coriander",
      "2 tablespoons of my ghee",
      "Salt, to taste",
      "Chicken stock cube",
    ],
    preparation_steps: [
      "1- The molokhia is placed in a saucepan over the fire, gradually adding water and stirring until obtaining the desired consistency, provided that the texture is not too heavy or light",
      "2- Add the stock cube, and leave the molokhia until it boils once, then remove from the heat",
      "3- In a frying pan over the fire, minced garlic is added to the ghee, stirring until golden",
      "4- Add the coriander to the garlic and stir until browned",
      "5- Add the mallow to the above, stir, then add salt to taste, and stir",
      "6- Put the mallow into a serving dish",
    ],
    side_dishes: "Rice with vermicelli",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [40, 70, 100, 140, 180],
    created_at: {
      order: "7",
    },
  },

  {
    id: 8,
    type: "lunch",
    category: "oriental",
    country: "Syrian",
    title: "Kabab Hindi",
    description:
      "In general, kebabs are considered one of the best foods and are most requested in restaurants and at parties or events and parties. Indian kebabs are among the most famous types of kebabs, which in some countries are called Dawood Pasha",
    getImageSrc: () => require("../images/kabab_hindi.jpg"),
    ingrediants: [
      "kg minced lamb (10% fat)",
      "2 tablespoons toasted pine nuts",
      "1½ kg tomatoes, peeled and cut into squares",
      "2 sliced onions",
      "6 garlic cloves, cut into thin slices",
      "1 green bell pepper, seeded and sliced",
      "1 red capsicum, seeded and sliced",
      "½ teaspoon ground ginger",
      "½ teaspoon ground cardamom",
      "½ teaspoon black pepper",
      "a pinch of cinnamon",
      "1 tablespoon of tomato puree",
      "1 teaspoon hot red pepper paste",
      "Salt, to taste",
      "2 tablespoons of vegetable oil",
    ],
    preparation_steps: [
      "1- Heat the oil in a large saucepan and stir-fry the garlic and onions until soft and translucent, then add the tomatoes and cook for 30 minutes over low heat",
      "2- In a bowl, mix the meat with 1 tablespoon of pine nuts, add ½ teaspoon of salt and ¼ teaspoon of black pepper, and shape the meat into small fingers",
      "3- Add black pepper, ginger, cinnamon and cardamom to the tomato casserole, add salt and red pepper paste, then add the puree of tomatoes, red and green peppers and cook for 15 minutes, then remove the saucepan from the heat",
      "4- Transfer the mixture to an oven tray, place the meat fingers on it, and cook for 45 minutes in a preheated oven to 180 degrees Celsius, making sure to turn the meat fingers after the first 20 minutes",
      "5- We distribute the remaining pine nuts on top and serve it with rice on the side",
    ],
    side_dishes: "Rice with vermicelli",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [35, 50, 75, 100, 125],
    created_at: {
      order: "8",
    },
  },

  {
    id: 9,
    type: "lunch",
    category: "western",
    country: "American",
    title: "Mushroom Soup",
    description:
      "A warm bowl of soup so deliciously creamy with tender bites of mushroom pieces",
    getImageSrc: () => require("../images/mashroom_soup.jpg"),
    ingrediants: [
      "90 grams of butter",
      "2 medium sized onions, cut into small pieces",
      "1 piece of crushed garlic",
      "500 grams of mushrooms, cut into small pieces (to taste)",
      "2 tablespoons of flour",
      "A cup of chicken stock or one cube of Maggi cubes",
      "1 bay leaf",
      "4 tablespoons of cream",
      "A small bunch of chopped parsley (optional)",
    ],
    preparation_steps: [
      "1- Place the butter in a soup pot over medium heat until it melts",
      "2- Add the onions and garlic for 8-10 minutes, making sure the garlic and onions have wilted without turning brown",
      "3- Then add the mushrooms and raise the heat for 3 minutes or until the mushrooms have softened",
      "4- Put the flour into the soup pot, stirring to combine all the ingredients with the flour",
      "5- Put the chicken stock and bay leaf inside the soup pot and leave the mixture until the soup begins to boil, then leave it for 10 minutes",
      "6- Then remove the bay leaf, then grind it",
      "7- Mix the soup the way you prefer either using an electric mixer or a hand mixer",
      "8- Heat the soup again and add the cream while stirring",
      "9- Add parsley and the soup is ready to be served",
    ],
    side_dishes: "",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [35, 50, 75, 100, 125],
    created_at: {
      order: "9",
    },
  },

  {
    id: 10,
    type: "lunch",
    category: "western",
    country: "American",
    title: "Chicken with Cream and Mushrooms",
    description:
      "Golden pan fried Chicken Breasts in an irresistible garlic sauce filled with caramelized onions and garlic",
    getImageSrc: () => require("../images/chicken_cream.jpg"),
    ingrediants: [
      "1 kilo chicken breast",
      "Salt, to taste",
      "One teaspoon of black pepper",
      "3 tablespoons of vegetable oil",
      "1 piece of (chopped) onion",
      "a can (cut into cubes) of mushrooms",
      "One teaspoon of white pepper",
      "3 cups of cooking cream",
    ],
    preparation_steps: [
      "1- To season the chicken: In a bowl, put the chicken breasts, season with salt and black pepper, and stir",
      "2- In a wide frying pan over medium heat, place the chicken breasts and cover the pan",
      "3- Leave the chicken on medium heat until cooked through, stirring occasionally",
      "4- Meanwhile, in a saucepan over medium heat, heat the vegetable oil and fry the onions until soft, then add the mushrooms and season with salt and white pepper",
      "5- Stir the ingredients for about 3 minutes, then add the cooking cream",
      "6- When the mixture boils, reduce the heat and add the grilled chicken breasts",
      "7- Leave the pot on medium heat for about 10 minutes",
      "8- Pour the chicken with the white cream in the serving dish",
    ],
    side_dishes: "White Rice",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [35, 50, 75, 100, 125],
    created_at: {
      order: "10",
    },
  },

  {
    id: 11,
    type: "lunch",
    category: "oriental",
    country: "Saudi",
    title: "Saudi Kabsa",
    description:
      "A meal consisting mainly of long-grain rice, which is served in the Arab Gulf countries, and is the main meal in Saudi Arabia and Kuwait",
    getImageSrc: () => require("../images/kabsa.jpg"),
    ingrediants: [
      "A quarter cup of butter",
      "1 kilo and 360 grams of chicken, cut into 8-10 pieces",
      "A large onion, finely chopped",
      "6 minced garlic cloves",
      "A quarter cup of mashed tomatoes",
      "397 grams of fresh or canned chopped tomatoes",
      "3 grains of grated carrots",
      "Two cloves",
      "A quarter teaspoon of grated nutmeg",
      "½ teaspoon ground cumin",
      "Half a teaspoon of ground coriander",
      "Salt and black pepper to taste",
      "4 cups of hot water",
      "Chicken bouillon cube",
      "Two and a quarter cups of basmati rice",
      "A quarter cup of raisins",
      "A quarter cup of roasted almond slices",
      "Half a teaspoon of saffron",
      "Half a teaspoon of ground cinnamon",
      "Half a teaspoon of ground spices",
      "Half a teaspoon of ground dried lemon",
      "A quarter teaspoon of ground green cardamom",
    ],
    preparation_steps: [
      "1- Melt the butter in a large saucepan",
      "2- Add the chicken pieces, garlic, and onions, and sauté until the onions soften and the chicken turns brown",
      "3- Add the tomato puree, and let it simmer for a few minutes",
      "4- Add the tomatoes, carrots, cloves, salt, pepper and the Kabsa spice mixture",
      "5- Cook the mixture for a few minutes",
      "6- Add the water and the chicken stock cube",
      "7- Bring the mixture to a boil, then reduce the heat and cover the pot",
      "8- Cook the mixture on low heat for 30 minutes",
      "9- Add the rice to the pot and stir well",
      "10- Cover the pot again",
      "11- Leave the mixture to cook over low heat for 35 to 40 minutes",
      "12- Add the raisins to the pot to cook for the last 10 minutes",
      "13- Cook the mixture until the rice is done",
      "14- Place the rice on a large serving plate, and garnish with the chicken and almonds",
      "15- Serve the Saudi Kabsa with the hot sauce",
    ],
    side_dishes: "Salad and Yogurt",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [20, 30, 50, 65, 80],
    created_at: {
      order: "11",
    },
  },

  {
    id: 12,
    type: "lunch",
    category: "western",
    country: "Mexican",
    title: "Fahita",
    description:
      "One of the most famous Mexican dishes spread in North America and all over the world. It has a distinct flavor and is quick to prepare",
    getImageSrc: () => require("../images/fahita.jpg"),
    ingrediants: [
      "A quarter cup of cheddar cheese",
      "One teaspoon each: ground cumin and sweet paprika powder",
      "Half a cup of yogurt",
      "Two pieces of boneless chicken breast",
      "A pinch of black pepper and salt",
      "A clove of crushed garlic",
      "One of each: red bell pepper and green bell pepper",
      "Onion",
      "Two tablespoons of olive oil",
    ],
    preparation_steps: [
      "1- Cut the onion into thin slices, and cut the chicken breast into long, thin slices",
      "2- Put each of: onions, two types of bell peppers and a spoonful of olive oil in a medium saucepan and put it on the fire for three minutes, then set the mixture aside",
      "3- Add each of: chicken, garlic, salt, black pepper and the remaining amount of olive oil to the same saucepan and mix the ingredients together and leave it on low heat until the chicken is cooked, then set the mixture aside",
      "4- Mix: pepper, yogurt, paprika, cumin and salt in a small saucepan",
    ],
    side_dishes: "Loaves of Tortilla",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [30, 55, 75, 95, 120],
    created_at: {
      order: "12",
    },
  },

  {
    id: 13,
    type: "lunch",
    category: "western",
    country: "Turkish",
    title: "Turkish lentil soup",
    description:
      "One of the vegetarian dishes with great benefits, and it is an ideal and distinctive dish in feeding vegetarians who do not eat animal proteins and is also suitable for dieting",
    getImageSrc: () => require("../images/lentils_soup.jpg"),
    ingrediants: [
      "1 cup of lentils",
      "1 tablespoon of butter",
      "1 tablespoon of flour",
      "1 tablespoon dried mint",
      "1 teaspoon of hot sauce",
      "1 tablespoon of tomato sauce",
      "1 teaspoon of paprika",
      "5 cups of broth",
    ],
    preparation_steps: [
      "1- Boil the lentils in water for 15 minutes, until softened",
      "2- In a bowl, melt the butter, then add the flour and stir for two minutes",
      "3- Add mint, chili, tomato sauce and paprika and stir well",
      "4- Add the lentils and broth, cover the pot and leave it on the stove until it gets hot",
      "5- Serve hot and garnish with lemon slices",
    ],
    side_dishes: "Fried Bread",
    url: () => "https://www.youtube.com/embed/Py3deTawqMc",
    price: [20, 45, 65, 85, 105],
    created_at: {
      order: "13",
    },
  },
];
export default LunchRecipesList;
